### ISSUE TITLE
About some code details?

### ISSUE THREAD

**Issue by ZhouMiaoGX** [ZouWang-spider/TCMT#1]
Hello, I am very interested in your work. Could you please provide more details on how to reproduce your research, such as how to use your code and the computational resources used during training?

**Comment by ZouWang-spider** [comment]
Tools such as YOLOv5, OCR, and Stanford CoreNLP are available tools that you can use. You can also try some advanced text-image representation tools, such as ViT, CLIP, and VLBERT, as they are easier to use.

**Comment by ZhouMiaoGX** [comment]
不好意思，我的英文不太好所以表述得可能不是很清楚。我现在想复现一下您训练模型的工作，但我发现代码里面有些绝对路径，不确定应该怎么本地化修改。还有就是不知道代码的主要文件在哪里，从哪个文件开始训练。以及我应该使用几个和什么型号的GPU才能达到您论文的精度？
![1735639359599](https://github.com/user-attachments/assets/72f1978e-3992-40ae-9fb7-7fa66d28b7cf)

**Comment by ZouWang-spider** [comment]
我刚看了一下，这个代码是之前的一个和图片上的方法有些不一样，Face_description这个是识别人物面部情绪（可以直接使用），Twitter15和17是需要你自己下载的数据集。代码中还有ViT模型处理图片，ViT-GPT2可以用于将生成图片的文本描述（同样需要去Huangface官网下载）,我没有使用GPU，你需要使用GPT可以将张量放在GPU设备上训练。

**Comment by ZhouMiaoGX** [comment]
能冒昧问一下您的pytorch和transformers的版本吗，我在修改好一些路径之后，报了新的错误

**Comment by ZouWang-spider** [comment]
尽量最新版本，Python环境高些，3.7会影响Scapy和transformers

**Comment by ZhouMiaoGX** [comment]
好的！因为我的java环境问题，我把BaseModel文件夹里的BiAffine.py文件里的代码    
text = nltk.word_tokenize(sentence)  
nlp = StanfordCoreNLP(r'D:\StanfordCoreNLP\stanford-corenlp-4.5.4', lang='en')
ann = nlp.pos_tag(sentence)
改成了ann = nltk.pos_tag(text)，试图用nltk来代替StanfordCoreNLP的词性标注功能。该函数的输入句子”"The quick brown fox jumps over the lazy dog."。输出为：[('The', 'DT'), ('quick', 'JJ'), ('brown', 'NN'), ('fox', 'NN'), ('jumps', 'VBZ'), ('over', 'IN'), ('the', 'DT'), ('lazy', 'JJ'), ('dog', 'NN'), ('.', '.')]。除此之外还解决了一些包循环引用问题。现在报错情况是：epoch:50:   0%|                                                                     | 0/50 [00:18<?, ?it/s]
Traceback (most recent call last):
  File "E:\vscode\TCMT\TCMT\TCMT.py", line 76, in <module>
    text_hidden = Cross_Transformers(text_feature_embedding, preds_embedding)
  File "E:\vscode\TCMT\TCMT\TextualModule.py", line 82, in Cross_Transformers
    text_hidden = featureinteraction(text_embedding, caption_embedding, caption_embedding)
  File "D:\torch\env\controlnet2\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\torch\env\controlnet2\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl    
    return forward_call(*args, **kwargs)
  File "E:\vscode\TCMT\TCMT\CrossTransformer.py", line 31, in forward
    attn_weights = torch.matmul(query_transformed, key_transformed.transpose(0, 1))
RuntimeError: mat1 and mat2 shapes cannot be multiplied (12288x1 and 768x10)
请问这怎么解决。是一定需要StanfordCoreNLP才可以复现您的结果吗？

**Comment by ZouWang-spider** [comment]
query_transformed维度为（12288x1）key_transformed维度为（768x10）这两个维度不匹配，自己定位到代码，解析器使用那种都可以不重要。

**Comment by ZouWang-spider** [comment]
训练的主函数中可能存在一些问题，这个是我之前的一份代码。其它的功能部件Biaffine、ViG、Corss Transformer你可以你可以拿去使用。

**Comment by ZhouMiaoGX** [comment]
好吧，感谢您的回答！我会继续尝试。
